### ISSUE TITLE
How can I use this to build a Mac pack?

### ISSUE THREAD

**Issue by acroca** [PeridexisErrant/starter-pack#20]
The latest mac pack is a bit old and not updated frequently, it'd be great to have a tool to generate it.
I've tried to use this to generate the mac version but I get some errors.

First I had to add the `extract_to` for PyLNP:
```yaml
        os-osx:
            extract_to: |
                PyLNP.app:build/starter-pack-launcher
```

and TwbT:
```yaml
        os-osx:
            extract_to: |
                {DFHACK_VER}/mousequery.plug.dylib:plugins/
                {DFHACK_VER}/twbt.plug.dylib:plugins/
```

The builder now runs and I get the following error:
```python-traceback
ERROR:  Could not extract: Dwarf Fortress, curr_baseline, graphics/ASCII, Legends Browser

Configuring pack...
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    stage.main()
  File "/starter_pack/starterpack/build.py", line 419, in main
    build_lnp_dirs()
  File "/starter_pack/starterpack/build.py", line 318, in build_lnp_dirs
    overwrite_dir(paths.lnp('extras'), paths.df())
  File "/starter_pack/starterpack/paths.py", line 64, in df
    return build('Dwarf Fortress ' + df_ver(), *paths)
  File "/starter_pack/starterpack/paths.py", line 44, in df_ver
    ver = component.ALL['Dwarf Fortress'].version
KeyError: 'Dwarf Fortress'
```

And I also get a warning: `WARNING:  "PyLNP.app" not found in "PyLNP_0.12b-OSX.zip"`, I guess the extract operation doesn't accept folders?

Has anyone succeeded building the mac pack?

Thanks!

**Comment by alexchandel** [comment]
@rgov has made a forked version with lots of macOS improvements: https://github.com/rgov/starter-pack/

@PeridexisErrant could you merge his changes into this repo?
